import { Property } from "@/types/property";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "1",
    slug: "appartement-meuble-fidjrosse-cotonou",
    title: "Appartement meublé 3 pièces à Fidjrossè",
    description: "Bel appartement entièrement meublé avec vue dégagée, situé dans un quartier calme de Fidjrossè. Cuisine équipée, salon spacieux, 2 chambres climatisées. Idéal pour expatriés ou séjour professionnel.",
    offerType: "louer",
    category: "appartement-meuble",
    price: 350000,
    surface: 85,
    bedrooms: 2,
    bathrooms: 1,
    location: "Fidjrossè, Cotonou",
    district: "Fidjrossè",
    city: "Cotonou",
    coordinates: { lat: 6.3456, lng: 2.3801 },
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    ],
    isFurnished: true,
    isAvailable: true,
    isFeatured: true,
    amenities: ["Climatisation", "Cuisine équipée", "Parking", "Gardien"],
    createdAt: "2026-03-01",
  },
  {
    id: "2",
    slug: "appartement-meuble-cadjehoun-cotonou",
    title: "Studio meublé standing à Cadjehoun",
    description: "Studio de standing entièrement équipé à Cadjehoun, proche des commerces et restaurants. Parfait pour un professionnel en déplacement.",
    offerType: "louer",
    category: "appartement-meuble",
    price: 200000,
    surface: 45,
    bedrooms: 1,
    bathrooms: 1,
    location: "Cadjehoun, Cotonou",
    district: "Cadjehoun",
    city: "Cotonou",
    coordinates: { lat: 6.3655, lng: 2.3933 },
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80",
    ],
    isFurnished: true,
    isAvailable: true,
    isFeatured: true,
    amenities: ["Climatisation", "Wi-Fi", "Eau chaude"],
    createdAt: "2026-03-05",
  },
  {
    id: "3",
    slug: "appartement-meuble-akpakpa-cotonou",
    title: "Appartement meublé 4 pièces à Akpakpa",
    description: "Grand appartement de 4 pièces entièrement meublé à Akpakpa. 3 chambres, 2 salles de bain, salon avec balcon. Quartier résidentiel sécurisé.",
    offerType: "louer",
    category: "appartement-meuble",
    price: 450000,
    surface: 120,
    bedrooms: 3,
    bathrooms: 2,
    location: "Akpakpa, Cotonou",
    district: "Akpakpa",
    city: "Cotonou",
    coordinates: { lat: 6.3700, lng: 2.4200 },
    images: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80",
      "https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800&q=80",
    ],
    isFurnished: true,
    isAvailable: true,
    isFeatured: false,
    amenities: ["Climatisation", "Balcon", "Parking", "Gardien", "Groupe électrogène"],
    createdAt: "2026-02-20",
  },
  {
    id: "4",
    slug: "appartement-non-meuble-fidjrosse",
    title: "Appartement non meublé 3 pièces à Fidjrossè",
    description: "Appartement neuf non meublé de 3 pièces avec finitions modernes. Idéal pour une famille souhaitant s'installer durablement.",
    offerType: "louer",
    category: "appartement-non-meuble",
    price: 150000,
    surface: 75,
    bedrooms: 2,
    bathrooms: 1,
    location: "Fidjrossè, Cotonou",
    district: "Fidjrossè",
    city: "Cotonou",
    coordinates: { lat: 6.3480, lng: 2.3780 },
    images: [
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=80",
    ],
    isFurnished: false,
    isAvailable: true,
    isFeatured: false,
    amenities: ["Parking", "Eau courante"],
    createdAt: "2026-02-15",
  },
  {
    id: "5",
    slug: "villa-meublee-haie-vive-cotonou",
    title: "Villa meublée de luxe à Haie Vive",
    description: "Magnifique villa de standing à Haie Vive, entièrement meublée avec goût. 4 chambres, piscine, jardin paysager, personnel de maison. Quartier diplomatique.",
    offerType: "louer",
    category: "villa-meublee",
    price: 800000,
    surface: 300,
    bedrooms: 4,
    bathrooms: 3,
    location: "Haie Vive, Cotonou",
    district: "Haie Vive",
    city: "Cotonou",
    coordinates: { lat: 6.3580, lng: 2.4100 },
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    ],
    isFurnished: true,
    isAvailable: true,
    isFeatured: true,
    amenities: ["Piscine", "Jardin", "Climatisation", "Groupe électrogène", "Gardien 24h", "Personnel"],
    createdAt: "2026-03-03",
  },
  {
    id: "6",
    slug: "villa-meublee-cocotiers-cotonou",
    title: "Villa meublée 3 chambres aux Cocotiers",
    description: "Villa contemporaine meublée dans le quartier prisé des Cocotiers. 3 chambres, 2 salles de bain, cuisine moderne, terrasse ombragée.",
    offerType: "louer",
    category: "villa-meublee",
    price: 600000,
    surface: 200,
    bedrooms: 3,
    bathrooms: 2,
    location: "Cocotiers, Cotonou",
    district: "Cocotiers",
    city: "Cotonou",
    coordinates: { lat: 6.3620, lng: 2.4050 },
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
    ],
    isFurnished: true,
    isAvailable: true,
    isFeatured: true,
    amenities: ["Terrasse", "Climatisation", "Parking", "Gardien"],
    createdAt: "2026-03-06",
  },
  {
    id: "7",
    slug: "villa-meublee-haie-vive-residence",
    title: "Résidence meublée haut standing Haie Vive",
    description: "Résidence de 5 chambres en duplex à Haie Vive. Finitions luxueuses, piscine privée, garage double. Idéale pour famille nombreuse ou représentation.",
    offerType: "louer",
    category: "villa-meublee",
    price: 750000,
    surface: 350,
    bedrooms: 5,
    bathrooms: 4,
    location: "Haie Vive, Cotonou",
    district: "Haie Vive",
    city: "Cotonou",
    coordinates: { lat: 6.3560, lng: 2.4080 },
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    ],
    isFurnished: true,
    isAvailable: true,
    isFeatured: false,
    amenities: ["Piscine", "Garage", "Climatisation", "Groupe électrogène", "Jardin"],
    createdAt: "2026-02-25",
  },
  {
    id: "8",
    slug: "terrain-calavi-500m2",
    title: "Terrain 500m² à Calavi — Titre foncier",
    description: "Terrain de 500m² avec titre foncier à Calavi, dans une zone en plein développement. Accès goudronné, réseau électrique à proximité. Parfait pour construction résidentielle.",
    offerType: "vendre",
    category: "terrain",
    price: 15000000,
    surface: 500,
    bedrooms: 0,
    bathrooms: 0,
    location: "Calavi",
    district: "Calavi",
    city: "Calavi",
    coordinates: { lat: 6.4300, lng: 2.3500 },
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80",
    ],
    isFurnished: false,
    isAvailable: true,
    isFeatured: true,
    amenities: ["Titre foncier", "Accès goudronné", "Électricité proche"],
    createdAt: "2026-03-02",
  },
  {
    id: "9",
    slug: "terrain-abomey-calavi-1000m2",
    title: "Terrain 1000m² à Abomey-Calavi",
    description: "Grand terrain de 1000m² à Abomey-Calavi, idéal pour projet immobilier. Zone résidentielle calme avec bon potentiel de valorisation.",
    offerType: "vendre",
    category: "terrain",
    price: 25000000,
    surface: 1000,
    bedrooms: 0,
    bathrooms: 0,
    location: "Abomey-Calavi",
    district: "Abomey-Calavi",
    city: "Abomey-Calavi",
    coordinates: { lat: 6.4500, lng: 2.3400 },
    images: [
      "https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800&q=80",
    ],
    isFurnished: false,
    isAvailable: true,
    isFeatured: false,
    amenities: ["Titre foncier", "Zone résidentielle"],
    createdAt: "2026-02-18",
  },
  {
    id: "10",
    slug: "terrain-calavi-lotissement",
    title: "Terrain 600m² lotissement viabilisé Calavi",
    description: "Parcelle de 600m² dans un lotissement viabilisé à Calavi. Eau, électricité et voirie déjà en place. Prêt à construire.",
    offerType: "vendre",
    category: "terrain",
    price: 20000000,
    surface: 600,
    bedrooms: 0,
    bathrooms: 0,
    location: "Calavi",
    district: "Calavi",
    city: "Calavi",
    coordinates: { lat: 6.4350, lng: 2.3550 },
    images: [
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80",
    ],
    isFurnished: false,
    isAvailable: true,
    isFeatured: true,
    amenities: ["Viabilisé", "Titre foncier", "Eau", "Électricité"],
    createdAt: "2026-03-04",
  },
  {
    id: "11",
    slug: "villa-vendre-cocotiers-cotonou",
    title: "Villa 4 chambres à vendre — Cocotiers",
    description: "Belle villa de 4 chambres à vendre dans le quartier des Cocotiers. Construction récente, finitions soignées, jardin arboré. Excellent investissement.",
    offerType: "vendre",
    category: "villa-non-meublee",
    price: 85000000,
    surface: 250,
    bedrooms: 4,
    bathrooms: 3,
    location: "Cocotiers, Cotonou",
    district: "Cocotiers",
    city: "Cotonou",
    coordinates: { lat: 6.3630, lng: 2.4060 },
    images: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
    ],
    isFurnished: false,
    isAvailable: true,
    isFeatured: false,
    amenities: ["Jardin", "Garage", "Terrasse", "Titre foncier"],
    createdAt: "2026-02-22",
  },
  {
    id: "12",
    slug: "villa-luxe-vendre-haie-vive",
    title: "Villa de luxe 5 chambres — Haie Vive",
    description: "Villa d'exception de 5 chambres à Haie Vive. Piscine, jardin paysager, finitions haut de gamme. Propriété rare sur le marché de Cotonou.",
    offerType: "vendre",
    category: "villa-non-meublee",
    price: 120000000,
    surface: 400,
    bedrooms: 5,
    bathrooms: 4,
    location: "Haie Vive, Cotonou",
    district: "Haie Vive",
    city: "Cotonou",
    coordinates: { lat: 6.3575, lng: 2.4095 },
    images: [
      "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80",
    ],
    isFurnished: false,
    isAvailable: true,
    isFeatured: false,
    amenities: ["Piscine", "Jardin paysager", "Garage double", "Titre foncier", "Groupe électrogène"],
    createdAt: "2026-02-10",
  },
];
